# Generated by Django 4.2.8 on 2023-12-20 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Votable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title to describe the votable content.', max_length=200)),
                ('text', models.TextField()),
                ('votable_type', models.CharField(choices=[('Question', 'QUESTION'), ('Statement', 'STATEMENT'), ('Proposal', 'PROPOSAL')], max_length=20)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('positive_votes', models.PositiveIntegerField(default=0)),
                ('negative_votes', models.PositiveIntegerField(default=0)),
                ('participation_percentage', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('positive_percentage', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('negative_percentage', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wilson_score', models.DecimalField(decimal_places=8, default=0.0, max_digits=10)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(1, 'POSITIVE'), (-1, 'NEGATIVE'), (0, 'NO_VOTE')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('votable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votable_app.votable')),
            ],
            options={
                'unique_together': {('user', 'votable')},
            },
        ),
    ]
